branches:
  only:
  - master
  
env:
 - CABALVER=1.24 GHCVER=8.0.2 LLVMVER=4.0
 
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH:$HOME/.cabal/bin:$PATH
 - travis_retry sudo apt-get install happy-1.19.5 alex-3.1.3
 - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-5 gcc-5
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
 
 # update llvm
 - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
 - travis_retry sudo add-apt-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise main"
 - travis_retry sudo add-apt-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-$LLVMVER main"
 - travis_retry sudo apt-get update
 - sudo apt-get install libedit-dev -y
 - sudo apt-get install -y llvm-$LLVMVER llvm-$LLVMVER-dev
 - alias llvm-config="llvm-config-4.0"
 - export PATH="/usr/bin:$PATH"

install:
 - sudo apt-get install haskell-platform -y
 - wget -qO- https://get.haskellstack.org/ | sh

script:
  - stack build
