name:                Haskull
version:             0.1.0.0
github:              "https://github.com/IITH-SBJoshi/haskell-11"
license:             BSD3
author:              "Vijay"
maintainer:          "cs17btech11040@iith.ac.in"
copyright:           "2019 Vijay"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/IITH-SBJoshi/haskell-11#readme>

dependencies:
- base >= 4.7 && < 5
- haskeline            >= 0.7.1.2
- llvm-hs              >= 4.0.0.0
- llvm-hs-pure         >= 4.0.0.0
- parsec               >= 3.1
- bytestring           >= 0.10
- mtl                  >= 2.1.3
- transformers         >= 0.3.0.0 && < 0.6
- containers           >= 0.4

library:
  source-dirs: src

executables:
  Haskull-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskull

tests:
  Haskull-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskull
