version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            add-apt-repository -y ppa:hvr/ghc
            apt-get update
            wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
            add-apt-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise main" -y
            add-apt-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main" -y
            apt-get update
            apt-get install libedit-dev -y
            apt-get install -y llvm-4.0 llvm-4.0-dev
            alias llvm-config="llvm-config-4.0"
            export PATH="/usr/bin:$PATH"
            apt-get install haskell-platform -y
            stack build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
